### ISSUE TITLE
nfhl_pipeline.py fails when using the Python 3.9 Dataflow base image

### ISSUE THREAD

**Issue by ZeroCool2u** [GoogleCloudPlatform/solutions-geospatial-analytics#2]
Beam SDK disconnects will cause the Dataflow pipeline to fail

**Comment by tjwebb** [comment]
Can you specify the command and input data you are using? It's not possible to debug with the information provided.

**Comment by ZeroCool2u** [comment]
Sorry, yeah this is a bit sparse. Basically I followed the instructions in the README, the only thing I did differently was use the Python 3.9 base image for data flow and that causes the process to fail outright. I made no other changes to the current process with the exception of removing that extra argument in the previous PR you merged before. I think if you were to rerun the pipeline with the latest data flow Python 3.9 image you should be able to replicate the issue. If it doesn't occur anymore then great, maybe it was just a temporary issue with the image.
